from setuptools import setup

setup(
    name='gmailApp',
    version='0.1',
    packages=['venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings', 'venv.lib.python2.7.site-packages.pip',
              'venv.lib.python2.7.site-packages.pip._vendor', 'venv.lib.python2.7.site-packages.pip._vendor.idna',
              'venv.lib.python2.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python2.7.site-packages.pip._vendor.certifi',
              'venv.lib.python2.7.site-packages.pip._vendor.chardet',
              'venv.lib.python2.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python2.7.site-packages.pip._internal', 'venv.lib.python2.7.site-packages.pip._internal.req',
              'venv.lib.python2.7.site-packages.pip._internal.vcs',
              'venv.lib.python2.7.site-packages.pip._internal.utils',
              'venv.lib.python2.7.site-packages.pip._internal.models',
              'venv.lib.python2.7.site-packages.pip._internal.commands',
              'venv.lib.python2.7.site-packages.pip._internal.operations', 'venv.lib.python2.7.site-packages.rsa',
              'venv.lib.python2.7.site-packages.tasks.vendoring', 'venv.lib.python2.7.site-packages.tests.unit',
              'venv.lib.python2.7.site-packages.tests.integration', 'venv.lib.python2.7.site-packages.wheel',
              'venv.lib.python2.7.site-packages.wheel.tool', 'venv.lib.python2.7.site-packages.wheel.signatures',
              'venv.lib.python2.7.site-packages.google.auth', 'venv.lib.python2.7.site-packages.google.auth.crypt',
              'venv.lib.python2.7.site-packages.google.auth.transport',
              'venv.lib.python2.7.site-packages.google.auth.compute_engine',
              'venv.lib.python2.7.site-packages.google.oauth2', 'venv.lib.python2.7.site-packages.pipenv',
              'venv.lib.python2.7.site-packages.pipenv.pew', 'venv.lib.python2.7.site-packages.pipenv.vendor',
              'venv.lib.python2.7.site-packages.pipenv.vendor.attr',
              'venv.lib.python2.7.site-packages.pipenv.vendor.idna',
              'venv.lib.python2.7.site-packages.pipenv.vendor.yarg',
              'venv.lib.python2.7.site-packages.pipenv.vendor.click',
              'venv.lib.python2.7.site-packages.pipenv.vendor.dotenv',
              'venv.lib.python2.7.site-packages.pipenv.vendor.jinja2',
              'venv.lib.python2.7.site-packages.pipenv.vendor.pytoml',
              'venv.lib.python2.7.site-packages.pipenv.vendor.certifi',
              'venv.lib.python2.7.site-packages.pipenv.vendor.chardet',
              'venv.lib.python2.7.site-packages.pipenv.vendor.chardet.cli',
              'venv.lib.python2.7.site-packages.pipenv.vendor.distlib',
              'venv.lib.python2.7.site-packages.pipenv.vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pipenv.vendor.iso8601',
              'venv.lib.python2.7.site-packages.pipenv.vendor.pexpect',
              'venv.lib.python2.7.site-packages.pipenv.vendor.pipreqs',
              'venv.lib.python2.7.site-packages.pipenv.vendor.urllib3',
              'venv.lib.python2.7.site-packages.pipenv.vendor.urllib3.util',
              'venv.lib.python2.7.site-packages.pipenv.vendor.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pipenv.vendor.urllib3.contrib._securetransport',
              'venv.lib.python2.7.site-packages.pipenv.vendor.urllib3.packages',
              'venv.lib.python2.7.site-packages.pipenv.vendor.urllib3.packages.backports',
              'venv.lib.python2.7.site-packages.pipenv.vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pipenv.vendor.colorama',
              'venv.lib.python2.7.site-packages.pipenv.vendor.pathlib2',
              'venv.lib.python2.7.site-packages.pipenv.vendor.requests',
              'venv.lib.python2.7.site-packages.pipenv.vendor.backports',
              'venv.lib.python2.7.site-packages.pipenv.vendor.backports.shutil_get_terminal_size',
              'venv.lib.python2.7.site-packages.pipenv.vendor.blindspin',
              'venv.lib.python2.7.site-packages.pipenv.vendor.packaging',
              'venv.lib.python2.7.site-packages.pipenv.vendor.markupsafe',
              'venv.lib.python2.7.site-packages.pipenv.vendor.ptyprocess',
              'venv.lib.python2.7.site-packages.pipenv.vendor.shellingham',
              'venv.lib.python2.7.site-packages.pipenv.vendor.shellingham.posix',
              'venv.lib.python2.7.site-packages.pipenv.vendor.shutilwhich',
              'venv.lib.python2.7.site-packages.pipenv.vendor.pythonfinder',
              'venv.lib.python2.7.site-packages.pipenv.vendor.pythonfinder.models',
              'venv.lib.python2.7.site-packages.pipenv.vendor.pythonfinder._vendor',
              'venv.lib.python2.7.site-packages.pipenv.vendor.pythonfinder._vendor.pep514tools',
              'venv.lib.python2.7.site-packages.pipenv.vendor.requirements',
              'venv.lib.python2.7.site-packages.pipenv.vendor.requirementslib',
              'venv.lib.python2.7.site-packages.pipenv.vendor.requirementslib.models',
              'venv.lib.python2.7.site-packages.pipenv.vendor.requirementslib._vendor',
              'venv.lib.python2.7.site-packages.pipenv.vendor.requirementslib._vendor.pipfile',
              'venv.lib.python2.7.site-packages.pipenv.vendor.click_completion',
              'venv.lib.python2.7.site-packages.pipenv.vendor.click_didyoumean',
              'venv.lib.python2.7.site-packages.pipenv.patched', 'venv.lib.python2.7.site-packages.pipenv.patched.pew',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.idna',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.pytoml',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.certifi',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.chardet',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.chardet.cli',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.distlib',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.msgpack',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.urllib3',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.urllib3.util',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.urllib3.packages',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.urllib3.packages.backports',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.colorama',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.html5lib',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.html5lib._trie',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.lockfile',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.progress',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.requests',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.packaging',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.cachecontrol',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.cachecontrol.caches',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.webencodings',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._vendor.pkg_resources',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._internal',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._internal.req',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._internal.vcs',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._internal.utils',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._internal.models',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._internal.commands',
              'venv.lib.python2.7.site-packages.pipenv.patched.notpip._internal.operations',
              'venv.lib.python2.7.site-packages.pipenv.patched.safety',
              'venv.lib.python2.7.site-packages.pipenv.patched.contoml',
              'venv.lib.python2.7.site-packages.pipenv.patched.contoml.file',
              'venv.lib.python2.7.site-packages.pipenv.patched.pipfile',
              'venv.lib.python2.7.site-packages.pipenv.patched.piptools',
              'venv.lib.python2.7.site-packages.pipenv.patched.piptools._compat',
              'venv.lib.python2.7.site-packages.pipenv.patched.piptools.scripts',
              'venv.lib.python2.7.site-packages.pipenv.patched.piptools.repositories',
              'venv.lib.python2.7.site-packages.pipenv.patched.prettytoml',
              'venv.lib.python2.7.site-packages.pipenv.patched.prettytoml.lexer',
              'venv.lib.python2.7.site-packages.pipenv.patched.prettytoml.parser',
              'venv.lib.python2.7.site-packages.pipenv.patched.prettytoml.tokens',
              'venv.lib.python2.7.site-packages.pipenv.patched.prettytoml.elements',
              'venv.lib.python2.7.site-packages.pipenv.patched.prettytoml.elements.traversal',
              'venv.lib.python2.7.site-packages.pipenv.patched.prettytoml.prettifier',
              'venv.lib.python2.7.site-packages.pyasn1', 'venv.lib.python2.7.site-packages.pyasn1.type',
              'venv.lib.python2.7.site-packages.pyasn1.codec', 'venv.lib.python2.7.site-packages.pyasn1.codec.ber',
              'venv.lib.python2.7.site-packages.pyasn1.codec.cer', 'venv.lib.python2.7.site-packages.pyasn1.codec.der',
              'venv.lib.python2.7.site-packages.pyasn1.codec.native', 'venv.lib.python2.7.site-packages.pyasn1.compat',
              'venv.lib.python2.7.site-packages.httplib2', 'venv.lib.python2.7.site-packages.apiclient',
              'venv.lib.python2.7.site-packages.cachetools', 'venv.lib.python2.7.site-packages.setuptools',
              'venv.lib.python2.7.site-packages.setuptools.extern',
              'venv.lib.python2.7.site-packages.setuptools._vendor',
              'venv.lib.python2.7.site-packages.setuptools._vendor.packaging',
              'venv.lib.python2.7.site-packages.setuptools.command', 'venv.lib.python2.7.site-packages.uritemplate',
              'venv.lib.python2.7.site-packages.oauth2client', 'venv.lib.python2.7.site-packages.oauth2client.contrib',
              'venv.lib.python2.7.site-packages.oauth2client.contrib.django_util',
              'venv.lib.python2.7.site-packages.pkg_resources', 'venv.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python2.7.site-packages.pyasn1_modules', 'venv.lib.python2.7.site-packages.googleapiclient',
              'venv.lib.python2.7.site-packages.googleapiclient.discovery_cache',
              'venv.lib.python2.7.site-packages.virtualenv_support', 'venv.local.lib.python2.7.site-packages.pip',
              'venv.local.lib.python2.7.site-packages.pip._vendor',
              'venv.local.lib.python2.7.site-packages.pip._vendor.idna',
              'venv.local.lib.python2.7.site-packages.pip._vendor.pytoml',
              'venv.local.lib.python2.7.site-packages.pip._vendor.certifi',
              'venv.local.lib.python2.7.site-packages.pip._vendor.chardet',
              'venv.local.lib.python2.7.site-packages.pip._vendor.chardet.cli',
              'venv.local.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.local.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.local.lib.python2.7.site-packages.pip._vendor.msgpack',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3.util',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3.packages',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.local.lib.python2.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.local.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.local.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.local.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.local.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.local.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.local.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.local.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.local.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.local.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.local.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.local.lib.python2.7.site-packages.pip._internal',
              'venv.local.lib.python2.7.site-packages.pip._internal.req',
              'venv.local.lib.python2.7.site-packages.pip._internal.vcs',
              'venv.local.lib.python2.7.site-packages.pip._internal.utils',
              'venv.local.lib.python2.7.site-packages.pip._internal.models',
              'venv.local.lib.python2.7.site-packages.pip._internal.commands',
              'venv.local.lib.python2.7.site-packages.pip._internal.operations',
              'venv.local.lib.python2.7.site-packages.rsa', 'venv.local.lib.python2.7.site-packages.wheel',
              'venv.local.lib.python2.7.site-packages.wheel.tool',
              'venv.local.lib.python2.7.site-packages.wheel.signatures',
              'venv.local.lib.python2.7.site-packages.google.auth',
              'venv.local.lib.python2.7.site-packages.google.auth.crypt',
              'venv.local.lib.python2.7.site-packages.google.auth.transport',
              'venv.local.lib.python2.7.site-packages.google.auth.compute_engine',
              'venv.local.lib.python2.7.site-packages.google.oauth2', 'venv.local.lib.python2.7.site-packages.pyasn1',
              'venv.local.lib.python2.7.site-packages.pyasn1.type',
              'venv.local.lib.python2.7.site-packages.pyasn1.codec',
              'venv.local.lib.python2.7.site-packages.pyasn1.codec.ber',
              'venv.local.lib.python2.7.site-packages.pyasn1.codec.cer',
              'venv.local.lib.python2.7.site-packages.pyasn1.codec.der',
              'venv.local.lib.python2.7.site-packages.pyasn1.codec.native',
              'venv.local.lib.python2.7.site-packages.pyasn1.compat', 'venv.local.lib.python2.7.site-packages.httplib2',
              'venv.local.lib.python2.7.site-packages.apiclient', 'venv.local.lib.python2.7.site-packages.cachetools',
              'venv.local.lib.python2.7.site-packages.setuptools',
              'venv.local.lib.python2.7.site-packages.setuptools.extern',
              'venv.local.lib.python2.7.site-packages.setuptools._vendor',
              'venv.local.lib.python2.7.site-packages.setuptools._vendor.packaging',
              'venv.local.lib.python2.7.site-packages.setuptools.command',
              'venv.local.lib.python2.7.site-packages.uritemplate',
              'venv.local.lib.python2.7.site-packages.oauth2client',
              'venv.local.lib.python2.7.site-packages.oauth2client.contrib',
              'venv.local.lib.python2.7.site-packages.oauth2client.contrib.django_util',
              'venv.local.lib.python2.7.site-packages.pkg_resources',
              'venv.local.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.local.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.local.lib.python2.7.site-packages.pkg_resources._vendor.packaging',
              'venv.local.lib.python2.7.site-packages.pyasn1_modules',
              'venv.local.lib.python2.7.site-packages.googleapiclient',
              'venv.local.lib.python2.7.site-packages.googleapiclient.discovery_cache'],
    url='https://github.com/SkYNewZ/python-scripts/tree/master/gmailApp',
    license='MIT',
    author='SkYNewZ',
    author_email='quentin@lemairepro.fr',
    description='A simple Python script for masse deleting emails'
)
